name: base
channels:
- conda-forge
dependencies:
- python=3.12
- pytest
- numpy
- matplotlib
- pandas
- seaborn
- scikit-learn
- statsmodels
- jupyter
- jupyterlab
- h5py
- pydot
- mlxtend
- numdifftools
- babel
- faker
- pip
- pip:
  - tensorflow # if no gpu
  - tensorboard
#  - tensorflow[and-cuda] # if want gpu support
