import numpy as np
import math
import random
from tqdm import tqdm
from babel.dates import format_date
from faker import Faker
from tensorflow.keras.utils import to_categorical
import tensorflow as tf
import tensorflow.keras.backend as K
from tensorflow import keras
from tensorflow.keras import layers


# ---------

# Define format of the data we would like to generate
FORMATS = ['short',
           'medium',
           'long',
           'full',
           'full',
           'full',
           'full',
           'full',
           'full',
           'full',
           'full',
           'full',
           'full',
           'd MMM YYY', 
           'd MMMM YYY',
           'dd MMM YYY',
           'd MMM, YYY',
           'd MMMM, YYY',
           'dd, MMM YYY',
           'd MM YY',
           'd MMMM YYY',
           'MMMM d YYY',
           'MMMM d, YYY',
           'dd.MM.YY']

# change this if you want it to work with another language
LOCALES = ['en_US']


def load_date(fake):
    """Load / generate some fake dates using rules for our date translation system.

    Parameters
    ----------
    fake : Faker() object
        A faker object from the fake package that can be used to generate fake date time objects.

    Returns
    -------
    (human_readable, machine_readable, date) : tuple (str, str, date_object)
        Returns a tuple containing a human readable string, a machine readable string
        and the actual machine datetime object these represent.
    """
    date = fake.date_object()

    try:
        human_readable = format_date(date, format=random.choice(FORMATS),  locale='en_US') # locale=random.choice(LOCALES))
        human_readable = human_readable.lower()
        human_readable = human_readable.replace(',','')
        machine_readable = date.isoformat()
        
    except AttributeError as e:
        return None, None, None

    return human_readable, machine_readable, date


def load_dataset(num_samples):
    """ "Loads" e.g. generates a dataset with num_samples examples.  A
    random dataset is generated by this function using some rules.

    Parameters
    ----------
    num_samples : int
        The size of the dataset to load / generate.

    Returns
    -------
    text_pairs : list of tuples (str, str)
        The dataset_pairs is a regular list of pairs of strings, the human and machine
        readable date strings respectively.
    """
    # the faker package is useful for generating fake data.  Set seeds here so this method
    # always returns the same fake generated dataset
    fake = Faker()
    Faker.seed(12345)
    random.seed(12345)

    text_pairs = []    

    # generate asked for number of samples, each call to load_date()
    # generates 1 sample
    for sample in tqdm(range(num_samples)):
        human_readable, machine_readable, _ = load_date(fake)
        if human_readable is not None:
            text_pairs.append((human_readable, 's' + machine_readable + 'e'))
    
    return text_pairs


def decode_sequence(model, input_sentence, source_sequence_length, source_vectorizor, target_sequence_length, target_vectorizor):
    """Use the trained encoder/decoder translator to translate the given
    input sentence in English for us.

    Parameters
    ----------
    model : Keras model
        A trained encoder / decoder model on the Date sequence translation task.
    input_sentence : str
        A string of the input human readable date sentence to be translated.
    source_vectorizor, target_vectorizor : TextVectorization
        The vectorizors used for source and targets, need both to first vectorize
        the given input sentence, then to decode the output sequence we get.
    """
    # create inverse lookup so can get an index and find the token from the target vocabulary
    target_vocab = target_vectorizor.get_vocabulary()
    target_index_lookup = dict(zip(range(len(target_vocab)), target_vocab))
    source_vocab_size = source_vectorizor.vocabulary_size()
    target_vocab_size = target_vectorizor.vocabulary_size()

    # the source vectorizor will normalize and tokenize sentence for us.
    tokenized_input_sentence = source_vectorizor([input_sentence])
    tokenized_input_sentence = to_categorical(tokenized_input_sentence, source_vocab_size)
    
    # we will gather the output of the decoder translation in this string, which initially only
    # has the special [start] seed token
    decoded_sentence = "s"
    for i in range(target_sequence_length):
        # basic inference, get prediction of next token from the trained model for the input
        # sentence, and what we have so far in the target translation sentence
        tokenized_target_sentence = target_vectorizor([decoded_sentence])[:,:-1]
        tokenized_target_sentence = to_categorical(tokenized_target_sentence, target_vocab_size)
        inputs = {
            'source_inputs': tokenized_input_sentence,
            'target_inputs': tokenized_target_sentence
        }
        next_token_predictions = model.predict(inputs, verbose=False)

        # convert next token prediction to a string.  argmax gives the token index
        # and use the reverse target vocabulary dictionary to look up the word string
        sampled_token_index = np.argmax(next_token_predictions[0, i, :])
        sampled_token = target_index_lookup[sampled_token_index]

        # we append the next predicted word to end of translated sentence so for
        decoded_sentence += sampled_token

        # we stop if see special [end] token, or loop will stop once we reach our maximum sentence length
        if sampled_token == "e":
            break

    # return the decoded/translated sentence
    return decoded_sentence

def decode_sequence_attention(model, input_sentence, source_sequence_length, source_vectorizor, target_sequence_length, target_vectorizor):
    """Use the trained encoder/decoder translator to translate the given
    input sentence in English for us.

    Parameters
    ----------
    model : Keras model
        A trained encoder / decoder model on the Date sequence translation task.
    input_sentence : str
        A string of the input human readable date sentence to be translated.
    source_vectorizor, target_vectorizor : TextVectorization
        The vectorizors used for source and targets, need both to first vectorize
        the given input sentence, then to decode the output sequence we get.
    """
    # create inverse lookup so can get an index and find the token from the target vocabulary
    target_vocab = target_vectorizor.get_vocabulary()
    target_index_lookup = dict(zip(range(len(target_vocab)), target_vocab))
    source_vocab_size = source_vectorizor.vocabulary_size()
    target_vocab_size = target_vectorizor.vocabulary_size()

    # the source vectorizor will normalize and tokenize sentence for us.
    tokenized_input_sentence = source_vectorizor([input_sentence])
    tokenized_input_sentence = to_categorical(tokenized_input_sentence, source_vocab_size)
    
    # kludge, we hardcode batch size of 25 in our model, so send in a batch of 24 empties with the one we want
    tokenized_input_sentence = np.vstack([tokenized_input_sentence,
                                          np.random.random((24, source_sequence_length, tokenized_input_sentence.shape[-1]))])

    # we will gather the output of the decoder translation in this string, which initially only
    # has the special [start] seed token
    decoded_sentence = "s"
    for i in range(target_sequence_length):
        # basic inference, get prediction of next token from the trained model for the input
        # sentence, and what we have so far in the target translation sentence
        tokenized_target_sentence = target_vectorizor([decoded_sentence])[:,:-1]
        tokenized_target_sentence = to_categorical(tokenized_target_sentence, target_vocab_size)
        tokenized_target_sentence = np.vstack([tokenized_target_sentence,
                                          np.random.random((24, target_sequence_length, tokenized_target_sentence.shape[-1]))])
        #print('input_sentence.shape:', tokenized_input_sentence.shape)
        #print('target_sentence.shape:', tokenized_target_sentence.shape)
        inputs = {
            'source_inputs': tokenized_input_sentence,
            'target_inputs': tokenized_target_sentence
        }
        next_token_predictions = model.predict(inputs, verbose=False)

        # convert next token prediction to a string.  argmax gives the token index
        # and use the reverse target vocabulary dictionary to look up the word string
        sampled_token_index = np.argmax(next_token_predictions[0, i, :])
        sampled_token = target_index_lookup[sampled_token_index]

        # we append the next predicted word to end of translated sentence so for
        decoded_sentence += sampled_token

        # we stop if see special [end] token, or loop will stop once we reach our maximum sentence length
        if sampled_token == "e":
            break

    # return the decoded/translated sentence
    return decoded_sentence


class TfStackWrapper(layers.Layer):
    def call(self, x):
        return tf.stack(x, axis=1)
   

def softmax(x, axis=1):
    """Custom softmax activation function, will perform softmax over axis other than last

    Parameters
    ----------
    x : Tensor.
    axis: Integer, axis along which the softmax normalization is applied.

    Returns
    -------
        Tensor, output of softmax transformation.

    Raises
    ------
        ValueError: In case `dim(x) == 1`.
    """
    ndim = K.ndim(x)
    if ndim == 2:
        return K.softmax(x)
    elif ndim > 2:
        e = K.exp(x - K.max(x, axis=axis, keepdims=True))
        s = K.sum(e, axis=axis, keepdims=True)
        return e / s
    else:
        raise ValueError('Cannot apply softmax to a tensor that is 1D')

class EveryNEpochs(keras.callbacks.Callback):
    """Subclass keras Callback to provide a callback to report loss and accuracy
    metrics at the end of every Nth epoch of training

    Attributes
    ----------
    N : int
       The epoch step size, we report metrics at the end of every Nth epoch of training. 
    """
    def __init__(self, N):
        """Chain the superclass constructor, add N attribute for this subclass.

        Parameters
        ----------
        N : int
           The epoch step size, report every N epochs evaluation metrics
        """
        super().__init__()
        self.N = N

    def on_epoch_end(self, epoch, logs={}):
        """Callback member override, called at the end of each epoch.
        We determine if the current epoch is divisible by our
        epoch step N, and if so display the metrics.  This callback
        assumes loss and accuracy are being monitored, and that validation
        data is being assessed during the training loop

        Parameters
        ----------
        epoch : int
           The current epoch number that just ended
        logs  : dict
           A dictionary like object.  The loss and accuracy metrics are assumed to be
           tracked, and further this callback assumes validation data is being used.
           So keys `loss`, `accuracy` are expected for the training data and
           `val_loss`, `val_accuracy` are expected for the validation data.
        """
        last_epoch = self.params['epochs'] - 1
        if epoch % self.N == 0 or epoch == (last_epoch):
            train_loss = logs.get('loss')
            train_accuracy = logs.get('accuracy')
            val_loss = logs.get('val_loss')
            val_accuracy = logs.get('val_accuracy')
            if val_accuracy == None:
                print(f"Epoch: {epoch:04d}/{last_epoch:04d}  training loss - {train_loss:0.4f}  training_accuracy - {train_accuracy:0.4f}")
            else:
                print(f"Epoch: {epoch:04d}/{last_epoch:04d}  training loss - {train_loss:0.4f}  validation loss - {val_loss:0.4f}  training_accuracy - {train_accuracy:0.4f}  validation accuracy - {val_accuracy:0.4f}")


def plot_history(ax, history_dict, metric_key):
    """Plot the asked for metrics. Usually we need to plot the metric from the training
    data and its corresponding measurement using the validation data, thus we pass in
    two keys for the training and validation metric to plot.

    Arguments
    ---------
    ax - a matplotlib figure axis to create plot onto
    history_dict - A Python dictionary whose keys should return list like enumerable
      items holding the measured metrics over some number of epochs of training.
    metric_key - The string key for the metric, validation data is assumed to be
      accessible as "val_" + metric_key


    """
    # setup epochs and keys/labels for the plot
    train_key = metric_key
    train_label = "Training " + metric_key
    val_key = "val_" + metric_key
    val_label = "Validation " + metric_key
    epochs = np.arange(1, len(history_dict[train_key]) + 1)
    
    # create the plot of the train and test metric
    ax.plot(epochs, history_dict[train_key], 'r-', label=train_label)
    ax.plot(epochs, history_dict[val_key], 'b-', label=val_label)
    ax.set_xlabel('Epochs')
    ax.set_ylabel(metric_key)
    #ax.set_xticks(epochs)
    ax.grid()
    ax.legend();

